### ISSUE TITLE
Container restart: Enter a Plugin ID from the list above or 'n': 

### ISSUE THREAD

**Issue by qwasy** [ntebis/octoeverywhere_bambulab_docker#2]
Whenever I restart the Container, I get the following message int the logs:

Enter a Plugin ID from the list above or 'n': 
Invalid input, try again.
If you need help, contact us! https://octoeverywhere.com/support

Obviously I can't input anything... 
When I recreate the container, I need to relink my printer with octoeverywhere again, which is annoying.

**Comment by ntebis** [comment]
I will have a look what I can do

**Comment by ntebis** [comment]
So I fixed the restarting the container bug, however about the recreation of the container is a bit more complicated and it will require changes to Octoeverywhere's source code. 

Since @QuinnDamerell is also working on creating an official container, you should direct your request to them. They are active at Octoeverywhere's discord

**Comment by ntebis** [comment]
So I fixed the restarting the container bug, however about the recreation of the container is a bit more complicated and it will require changes to Octoeverywhere's source code. 

Since @QuinnDamerell is also working on creating an official container, you should direct your request to them. They are active at Octoeverywhere's discord

**Comment by ntebis** [comment]
Latest container should have it.
